### ISSUE TITLE
Python 2 reached EOL

### ISSUE THREAD

**Issue by jgru** [dod-cyber-crime-center/sqlite-dissect#9]
Dear sqlite-dissect-maintainers,

first of all, thanks for providing such a great tool! 
Unfortunately, Python 2 reached its end of life a while ago. Are there any chances, that you will port the code to work with Python 3? Since, I saw that you work a lot with byte-strings, this might need numerous changes, I fear.

Thanks already in advance for considering this proposal.

Best regards
Jan

**Comment by DC3-DCCI** [comment]
Thanks for reporting this issue.  We are actively working on a branch to update to the latest version(s) of Python 3,x and testing it.  The main item causing this to take some time is the byte-strings as you have referenced.

**Comment by jgru** [comment]
Glad to hear! If there are any self-contained tasks, where I might jump in, please let me know.

**Comment by kchason** [comment]
I have developed a branch and am continuing testing before submitting the pull request to the maintainers. The current progress is available at: https://github.com/kchason/sqlite-dissect/pull/4. Note, this will be submitted against the primary repository and the draft pull above is just for easier comparison of the differences.

**Comment by kchason** [comment]
Python 3.12 support was just released in [`v1.0.0`](https://github.com/dod-cyber-crime-center/sqlite-dissect/releases/tag/v1.0.0)
